### ISSUE TITLE
私聊消息发送失败

### ISSUE THREAD

**Issue by VoxHwa** [lihongbin99/ChatGPT_to_WechatBot#1]
![image](https://user-images.githubusercontent.com/96711835/206710877-6b4c4882-878f-4522-b2b9-bc8ade88030b.png)

**Comment by lihongbin99** [comment]
你好，基于 [openwechat 源码中的 stringer.go 文件](https://github.com/eatmoreapple/openwechat/blob/master/stringer.go)来看，此错误的原因是调用微信接口后返回异常, 且 openwechat 目前暂无设置1204异常对应的是什么意思
在 [openwehcat的 Issuse](https://github.com/eatmoreapple/openwechat/issues) 中可以看到其他用户提问过这个问题, 具体详情请转移到
https://github.com/eatmoreapple/openwechat/issues/110
