### ISSUE TITLE
回复信息显示不全

### ISSUE THREAD

**Issue by wj2355021** [lihongbin99/ChatGPT_to_WechatBot#4]
![767723c85e220a5528abdb85c186de4](https://user-images.githubusercontent.com/32793452/206910613-733e5c93-a18e-4555-8628-e11f18f2ef96.jpg)

**Comment by wj2355021** [comment]
回复内容只显示一半
The reply is only half displayed

**Comment by lihongbin99** [comment]
你好，这是因为ChatGPT回复消息有长度限制，超过了限制就会被截断，你可以使用诸如"继续说", "继续讲"之类的话术再次询问ChatGPT以获取被截断的消息内容
