### ISSUE TITLE
启动不了报错如下

### ISSUE THREAD

**Issue by wj2355021** [lihongbin99/ChatGPT_to_WechatBot#5]
[root@nextcloud ChatGPT_to_WechatBot]# !go
go build -o gpt main.go
[root@nextcloud ChatGPT_to_WechatBot]# ./gpt 
2022/12/12 11:10:55 net/http: invalid byte '"' in Cookie.Value; dropping invalid bytes
2022/12/12 11:10:55 更新 Token 解析响应数据失败: invalid character '<' looking for beginning of value
2022/12/12 11:10:55 请输入任意字符退出程序

**Comment by lihongbin99** [comment]
新版以更新, 具体详情请[转移](https://github.com/lihongbin99/ChatGPT_to_WechatBot/issues/6)
