### ISSUE TITLE
检查open ai 的 cookie 步骤请求报错， 403

### ISSUE THREAD

**Issue by liuxiangxiangyuan** [lihongbin99/ChatGPT_to_WechatBot#6]
![image](https://user-images.githubusercontent.com/52985669/206963648-cf59b2e0-7c69-4a11-a6f2-532ab0923ff4.png)

**Comment by lihongbin99** [comment]
OpenAi的接口更新了
- 需要在请求cookie中添加cf_clearance
- 在浏览器上登录ChatGPT获取cookie数据时的User_Agent必须跟调用接口时的User_Agent一致
- 在浏览器上登录ChatGPT获取cookie数据时的ip必须跟调用接口的ip一致

## 你在idea调试的时候, 注意避免网络走idea设置中下载插件的代理配置造成的ip不一致问题
